### ISSUE TITLE
DSP-W218 support

### ISSUE THREAD

**Issue by mario-mk** [LinuxChristian/pyW215#38]
Dear developers, 
I was wondering about possible support of dlink DSP-W218 Smart Plugs. It's completely different comparing to 215 which is already end of sale and support. Have you made any research on this?
regards

**Comment by jolaca01** [comment]
Hi, DLink DSPW118 is a nice compact and even cheap smart plug, I would also like if you could add support for it in your Dlink HA integration. Thanks @LinuxChristian

**Comment by LinuxChristian** [comment]
Hi @mario-mk and @jolaca01,

Thanks for the suggestion. Unfortunately, I do not own a DSP-W218 so it's impossible for me to develop an interface for it. As I understand, the new versions of DLink have also completely changed the protocol compared to the old W215. So I don't except it's possible to reuse much of the existing code for the W218.

If you dig a bit more into it and find some API documentation I would be happy to review a PR. Otherwise, you might be able to use a different Python library that goes through the D-link cloud: https://github.com/ageof/MyDlink-API-Python

**Comment by midtskogen** [comment]
I just got hold of a W218 and indeed it's totally different.  All TCP ports are closed, but UDP port 52644 is open.  That's all I have.  This is after configuring it to connect to my wifi.

**Comment by LinuxChristian** [comment]
Thanks for the info, @midtskogen. I have added a note to the readme about support for W218.

There isn't anything more to do about this issue so I am going to close it. Please, reopen or keep commenting if you find more information about the topic.

**Comment by kentthoresen-x** [comment]
DId enyone figure this out i just got one of these.

**Comment by LinuxChristian** [comment]
@kentthoresen-x, unfortunately this library will not support W218 as the firmware is completely different compared to the W215. My best suggestion is to have a look at this project: https://github.com/ageof/MyDlink-API-Python
