### ISSUE TITLE
Invalid Temperature Returned

### ISSUE THREAD

**Issue by GreenKudu** [LinuxChristian/pyW215#8]
Using the code with a recently purchased W215 with a 2.02 firmware, the temperature returned is always in the range of 10 to 12. Other values such as Consumption or Total Consumption seem correct, but Temperature is not. Is this correct? How should I interpret this value?

**Comment by LinuxChristian** [comment]
My temperature range is 99% of the time between 30 - 40 degrees Celsius, My rooms are perhaps only 20 degree Celsius but I think the switches generate quite some heat just sitting in the socket. I have a switch from the EU. If you got yours from outside the EU it may report Fahrenheit but then I would expect a greater number then 12.

I would suggest placing the switch either a really cold or warm place and see if it changes outside the 10-12 (Celsius??) range. If you have a long extension cord perhaps your fridge or a cold basement with a wireless connection?
You could also try downloading the D-Link mobile app and connect to the switch via their cloud solution to see it that reports a different temperature. If you get a different number than pyW215 then we can begin debugging otherwise your switch might be broken.

Let me know how it goes and then I will help you through the debugging if you think pyW215 is to blame :smile:

**Comment by GreenKudu** [comment]
Thanks a lot for your feedback!

After your message, I finally sat down, factory reset the plug, got the damn Android app to pair with the plug, which I had been unable to do until now, even though I was able to connect your library to the plug since day 1 :smile:

The first thing the app did after pairing was upgrade the firmware of the plug to v2.22. I thought that this might break pyW215 but it does work correctly with this firmware version!

After updating the firmware the temperature values are now correctly reported by pyW215 - or at least they match the value in the app which in my case is 54º. Case closed!

**Comment by LinuxChristian** [comment]
Great you got it working!

I have added a comment to the readme about upgrading the firmware in case of problems. Hopefully that should aid any other users who have similar problems.
